using System.Text.Json;
using CharacterWizard.Shared.Models;

namespace CharacterWizard.Shared.Export;

/// <summary>
/// Imports a <see cref="Character"/> from a JSON string produced by the wizard's built-in
/// "Export JSON" function, which uses <see cref="JsonSerializer.Serialize{T}"/>.
/// </summary>
/// <remarks>
/// The JSON format is a direct serialization of the <see cref="Character"/> object using the
/// default <see cref="JsonSerializer"/> settings (PascalCase property names, no special
/// converters). Case-insensitive property matching is enabled so that files generated by
/// slightly different serialization settings (e.g. camelCase) are still accepted.
/// </remarks>
public class CharacterJsonImporter
{
    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    /// <summary>
    /// Deserializes a <see cref="Character"/> from the supplied JSON string.
    /// </summary>
    /// <param name="json">JSON string to deserialize.</param>
    /// <returns>
    /// The deserialized <see cref="Character"/>, or <c>null</c> if the input is empty,
    /// not valid JSON, or does not represent a <see cref="Character"/> object.
    /// </returns>
    public Character? Import(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
            return null;

        try
        {
            return JsonSerializer.Deserialize<Character>(json, Options);
        }
        catch
        {
            return null;
        }
    }
}
